FROM ruby:3.3.6

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev postgresql-client

WORKDIR /myapp

# bundler
RUN gem install bundler

# Gemfileだけ先にコピー（キャッシュ効く）
#COPY Gemfile Gemfile.lock ./
#RUN bundle install

# 残りのRailsコード
COPY . .
